# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The A-Team Adventures
email: armidson89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        The place to visit to see what adventure the A-Team are up to next.
        We could be coming to a country near you!
baseurl: "/n3wmsy/n3wmsy.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  n3wmsy

# Build settings
markdown: kramdown
